services:
  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=shortlink
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - shortlink-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d shortlink"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 30s

  app:
    build: 
      context: .
      dockerfile: Dockerfile
    image: mishazx/shortlinkspring:latest
    ports:
      - "8999:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/shortlink
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE=10
      - SPRING_DATASOURCE_HIKARI_MINIMUM_IDLE=5
      - SPRING_DATASOURCE_HIKARI_IDLE_TIMEOUT=300000
      - SPRING_DATASOURCE_HIKARI_CONNECTION_TIMEOUT=20000
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver
    networks:
      - shortlink-network
    restart: on-failure

volumes:
  postgres_data:

networks:
  shortlink-network:
    driver: bridge