version: '3.8'
services:
  postgres:
    # ... существующая конфигурация PostgreSQL ...

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data: 